module.exports = {
	'prefer-rest-params': 1,
	'prefer-spread': 1,
	'require-await': 2,
	'spaced-comment': 1,
	yoda: 2,
	'prefer-const': 1,
	'prefer-object-spread': 2,
	'no-useless-concat': 1,
	'no-throw-literal': 1,
	'no-redeclare': 2,
	'no-multi-assign': 2,
	'max-params': ['warn', 3],
	'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
	'space-in-parens': ['warn', 'never'],
	'comma-spacing': 1,
	'sort-vars': 1,
	'no-labels': ['error'],
	'max-classes-per-file': ['error', 1],
	'object-curly-spacing': [1, 'always'],
	'no-duplicate-imports': 2,
	'array-callback-return': 1,
	'no-constant-binary-expression': 1,
	'no-constructor-return': 2,
	'no-promise-executor-return': 2,
	'no-self-compare': 2,
	'no-unreachable-loop': 2,
	'class-methods-use-this': 1,
	'consistent-return': 1,
	'default-case-last': 1,
	'default-param-last': 1,
	eqeqeq: 2,
	'new-cap': 1,
	'no-confusing-arrow': 1,
	'no-eq-null': 1,
	'no-lone-blocks': 1,
	'no-mixed-operators': 1,
	'no-multi-str': 2,
	'no-plusplus': 1,
	'no-return-assign': 2,
	'no-unneeded-ternary': 2,
	'no-var': 2,
	'no-with': 2,
	'no-unused-vars': 'warn',
	'prefer-regex-literals': 2,
	quotes: [1, 'single'],
	'jsonc/quotes': ['error', 'double', { 'avoidEscape': false }]
};
